### ISSUE TITLE
code used for creating metapsy variables

### ISSUE THREAD

**Issue by clara-miguel** [metapsy-project/data-inpatients#2]
Hi @MathiasHarrer 
I wanted to ask if you could share the code that you used for creating the metapsy variables. I just updated the package using this commands (see below), but I can't create the new metapsy variables (.g, .g_se). Also, the binaryES function doesn't work. Am I maybe using an older version of metapsyTools?

if (!require("devtools"))
  install.packages("devtools")

devtools::install_github(
 "metapsy-project/metapsyTools",
   build_vignettes = TRUE)

**Comment by MathiasHarrer** [comment]
Hi Clara,

no problem. The current version of MPT that I am using (1.0.1) has not been released yet, because it contains major changes that are incompatible with older versions (e.g. RR calculations, integration of the metapsy data standard, etc.). I have not released it yet because no data following the metapsy data standard has been released yet. We have two options:

- I release the package so you can download it, but that means that everyone can already see the new version
- I send you the package as a so called "tar.gz" (essentially a zip-Folder), which you can download and then allows you to install the new version locally on you computer. I can show you how to do that.

Both options are fine with. Let me know what you think.

**Comment by clara-miguel** [comment]
Oh no problem! I thought I was doing something wrong. I am fine with any of both options, but maybe you prefer me to install it locally in my computer so that the new version doesn't have to be released yet? I am just using it to format some other datasets to the current standards and see if it works!

**Comment by clara-miguel** [comment]
@cyplessen this interests you as well :)

**Comment by MathiasHarrer** [comment]
Alrighty, here's the package: https://we.tl/t-Z2nxah8V2J
It's a .zip, not a tar.gz. The former can be install using `devtools::install_local`

You only have to set the right path.

```r
devtools::install_local("~/Downloads/metapsyTools.zip")
```

**Comment by clara-miguel** [comment]
Thank you so much! It worked 👯‍♀️  Only one last question: if Pim wants to run analyses with metapsyTools with the new datasets that have the .g and .g_se variables, he should also download the package locally on his computer, right? Or well, change the name of all the variables so that they fit the older metapsyTools standards.

**Comment by MathiasHarrer** [comment]
Yes, exactly. On the other hand, once the inpatients dataset is released I see no reason not to release metapsyTools :)

**Comment by clara-miguel** [comment]
@MathiasHarrer I have the json file for description of variables almost finished, but I saw a little problem in the final dataset and I want to modify this before releasing it (i.e. baseline data was available only for one group)
